# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.MediaPlayer = QtWidgets.QFrame(self.centralwidget)
        self.MediaPlayer.setMinimumSize(QtCore.QSize(480, 50))
        self.MediaPlayer.setMaximumSize(QtCore.QSize(16777215, 56))
        self.MediaPlayer.setStyleSheet("")
        self.MediaPlayer.setObjectName("MediaPlayer")
        self.mediaControlHorizontalLayout_3 = QtWidgets.QHBoxLayout(self.MediaPlayer)
        self.mediaControlHorizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.mediaControlHorizontalLayout_3.setSpacing(0)
        self.mediaControlHorizontalLayout_3.setObjectName("mediaControlHorizontalLayout_3")
        self.MediaController_2 = QtWidgets.QFrame(self.MediaPlayer)
        self.MediaController_2.setMinimumSize(QtCore.QSize(480, 50))
        self.MediaController_2.setMaximumSize(QtCore.QSize(680, 56))
        self.MediaController_2.setStyleSheet("QFrame {\n"
"    background-color: #111111;\n"
"    font-family: \"Helvetica\", sans-serif;\n"
"}\n"
"")
        self.MediaController_2.setObjectName("MediaController_2")
        self.mediaPlayerVerticalLayout_2 = QtWidgets.QVBoxLayout(self.MediaController_2)
        self.mediaPlayerVerticalLayout_2.setContentsMargins(1, 0, 1, 0)
        self.mediaPlayerVerticalLayout_2.setSpacing(0)
        self.mediaPlayerVerticalLayout_2.setObjectName("mediaPlayerVerticalLayout_2")
        self.MediaProgressBar_2 = QtWidgets.QFrame(self.MediaController_2)
        self.MediaProgressBar_2.setStyleSheet("QSlider { background: transparent; height: 6px; } QSlider::groove:horizontal { border: none; height: 4px; background: #f0f0f0; border-radius: 2px; } QSlider::handle:horizontal:hover { background: #388e3c; } QSlider::sub-page:horizontal { background: #4caf50; border-radius: 2px; }")
        self.MediaProgressBar_2.setObjectName("MediaProgressBar_2")
        self.mediaProgressBarHorizontalLayout_2 = QtWidgets.QHBoxLayout(self.MediaProgressBar_2)
        self.mediaProgressBarHorizontalLayout_2.setContentsMargins(8, 0, 8, 0)
        self.mediaProgressBarHorizontalLayout_2.setSpacing(8)
        self.mediaProgressBarHorizontalLayout_2.setObjectName("mediaProgressBarHorizontalLayout_2")
        self.playbackTimeLabel_2 = QtWidgets.QLabel(self.MediaProgressBar_2)
        self.playbackTimeLabel_2.setMinimumSize(QtCore.QSize(30, 16))
        self.playbackTimeLabel_2.setMaximumSize(QtCore.QSize(36, 16))
        self.playbackTimeLabel_2.setStyleSheet("QLabel {\n"
"background: transparent;\n"
"color: #FFEEDD;\n"
"font-family: \"Helvetica\", sans-serif;\n"
"}")
        self.playbackTimeLabel_2.setObjectName("playbackTimeLabel_2")
        self.mediaProgressBarHorizontalLayout_2.addWidget(self.playbackTimeLabel_2)
        self.playbackProgress_2 = QtWidgets.QSlider(self.MediaProgressBar_2)
        self.playbackProgress_2.setMinimumSize(QtCore.QSize(380, 8))
        self.playbackProgress_2.setMaximumSize(QtCore.QSize(16777215, 8))
        self.playbackProgress_2.setStyleSheet("QSlider {\n"
"    background: transparent;\n"
"    height: 8px;\n"
"}\n"
"\n"
"QSlider::groove:horizontal {\n"
"    border: none;\n"
"    height: 6px;\n"
"    background: #33383E; /* Set the same background color as your QProgressBar */\n"
"    border-radius: 2px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"    width: 0px; /* Set the width of the circular handle */\n"
"    background: #4455FF; /* Set the same hover color as your QProgressBar */\n"
"    border-radius: 6px; /* Make it circular by setting half of the width/height */\n"
"}\n"
"\n"
"QSlider::sub-page:horizontal {\n"
"    background: #F1594B; /* Set the same filled portion color as your QProgressBar */\n"
"    border-radius: 2px;\n"
"}\n"
"")
        self.playbackProgress_2.setMaximum(499)
        self.playbackProgress_2.setOrientation(QtCore.Qt.Horizontal)
        self.playbackProgress_2.setObjectName("playbackProgress_2")
        self.mediaProgressBarHorizontalLayout_2.addWidget(self.playbackProgress_2)
        self.mediaLenghtLabel_2 = QtWidgets.QLabel(self.MediaProgressBar_2)
        self.mediaLenghtLabel_2.setMinimumSize(QtCore.QSize(30, 16))
        self.mediaLenghtLabel_2.setMaximumSize(QtCore.QSize(36, 16))
        self.mediaLenghtLabel_2.setStyleSheet("QLabel {\n"
"background: transparent;\n"
"color: #FFEEDD;\n"
"font-family: \"Helvetica\", sans-serif;\n"
"}")
        self.mediaLenghtLabel_2.setObjectName("mediaLenghtLabel_2")
        self.mediaProgressBarHorizontalLayout_2.addWidget(self.mediaLenghtLabel_2)
        self.mediaProgressBarHorizontalLayout_2.setStretch(1, 12)
        self.mediaPlayerVerticalLayout_2.addWidget(self.MediaProgressBar_2)
        self.MediaButtons_2 = QtWidgets.QFrame(self.MediaController_2)
        self.MediaButtons_2.setStyleSheet("QFrame {\n"
"    background-color: #0F111A; \n"
"}\n"
"\n"
"QPushButton { \n"
"    background: transparent; border: none;  border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color:#33383E; \n"
"    border-style: solid; \n"
"    border-radius: 2px; \n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"     background-color: #4455FF; \n"
"    border-style: solid; \n"
"    border-radius: 2px; \n"
"}")
        self.MediaButtons_2.setObjectName("MediaButtons_2")
        self.mediaButtonsHorizontalLayout_2 = QtWidgets.QHBoxLayout(self.MediaButtons_2)
        self.mediaButtonsHorizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.mediaButtonsHorizontalLayout_2.setSpacing(2)
        self.mediaButtonsHorizontalLayout_2.setObjectName("mediaButtonsHorizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.mediaButtonsHorizontalLayout_2.addItem(spacerItem)
        self.fileOpenerButton_2 = QtWidgets.QPushButton(self.MediaButtons_2)
        self.fileOpenerButton_2.setMinimumSize(QtCore.QSize(24, 24))
        self.fileOpenerButton_2.setMaximumSize(QtCore.QSize(24, 24))
        self.fileOpenerButton_2.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/cil-folder-open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.fileOpenerButton_2.setIcon(icon)
        self.fileOpenerButton_2.setObjectName("fileOpenerButton_2")
        self.mediaButtonsHorizontalLayout_2.addWidget(self.fileOpenerButton_2)
        self.pushButton_2 = QtWidgets.QPushButton(self.MediaButtons_2)
        self.pushButton_2.setMinimumSize(QtCore.QSize(24, 24))
        self.pushButton_2.setMaximumSize(QtCore.QSize(24, 24))
        self.pushButton_2.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/cil-lock-locked.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon1)
        self.pushButton_2.setObjectName("pushButton_2")
        self.mediaButtonsHorizontalLayout_2.addWidget(self.pushButton_2)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.mediaButtonsHorizontalLayout_2.addItem(spacerItem1)
        self.mediaTitle_2 = QtWidgets.QLabel(self.MediaButtons_2)
        self.mediaTitle_2.setMinimumSize(QtCore.QSize(60, 0))
        self.mediaTitle_2.setStyleSheet("QLabel {\n"
"background: transparent;\n"
"color: #FFEEDD;\n"
"font-family: \"Helvetica\", sans-serif;\n"
"}")
        self.mediaTitle_2.setObjectName("mediaTitle_2")
        self.mediaButtonsHorizontalLayout_2.addWidget(self.mediaTitle_2)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.mediaButtonsHorizontalLayout_2.addItem(spacerItem2)
        self.mediaPreviousButton_2 = QtWidgets.QPushButton(self.MediaButtons_2)
        self.mediaPreviousButton_2.setMinimumSize(QtCore.QSize(24, 24))
        self.mediaPreviousButton_2.setMaximumSize(QtCore.QSize(24, 24))
        self.mediaPreviousButton_2.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/cil-media-step-backward.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mediaPreviousButton_2.setIcon(icon2)
        self.mediaPreviousButton_2.setIconSize(QtCore.QSize(20, 20))
        self.mediaPreviousButton_2.setObjectName("mediaPreviousButton_2")
        self.mediaButtonsHorizontalLayout_2.addWidget(self.mediaPreviousButton_2)
        self.mediaPlayPauseButton_2 = QtWidgets.QPushButton(self.MediaButtons_2)
        self.mediaPlayPauseButton_2.setMinimumSize(QtCore.QSize(24, 24))
        self.mediaPlayPauseButton_2.setMaximumSize(QtCore.QSize(24, 24))
        self.mediaPlayPauseButton_2.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons/cil-media-play.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mediaPlayPauseButton_2.setIcon(icon3)
        self.mediaPlayPauseButton_2.setIconSize(QtCore.QSize(20, 20))
        self.mediaPlayPauseButton_2.setObjectName("mediaPlayPauseButton_2")
        self.mediaButtonsHorizontalLayout_2.addWidget(self.mediaPlayPauseButton_2)
        self.mediaNextButton_2 = QtWidgets.QPushButton(self.MediaButtons_2)
        self.mediaNextButton_2.setMinimumSize(QtCore.QSize(24, 24))
        self.mediaNextButton_2.setMaximumSize(QtCore.QSize(24, 24))
        self.mediaNextButton_2.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/icons/cil-media-step-forward.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mediaNextButton_2.setIcon(icon4)
        self.mediaNextButton_2.setIconSize(QtCore.QSize(20, 20))
        self.mediaNextButton_2.setObjectName("mediaNextButton_2")
        self.mediaButtonsHorizontalLayout_2.addWidget(self.mediaNextButton_2)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.mediaButtonsHorizontalLayout_2.addItem(spacerItem3)
        self.mediaRepeatButton_2 = QtWidgets.QPushButton(self.MediaButtons_2)
        self.mediaRepeatButton_2.setMinimumSize(QtCore.QSize(24, 24))
        self.mediaRepeatButton_2.setMaximumSize(QtCore.QSize(24, 24))
        self.mediaRepeatButton_2.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/icons/cil-loop.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mediaRepeatButton_2.setIcon(icon5)
        self.mediaRepeatButton_2.setIconSize(QtCore.QSize(20, 20))
        self.mediaRepeatButton_2.setObjectName("mediaRepeatButton_2")
        self.mediaButtonsHorizontalLayout_2.addWidget(self.mediaRepeatButton_2)
        self.mediaShuffleButton_2 = QtWidgets.QPushButton(self.MediaButtons_2)
        self.mediaShuffleButton_2.setMinimumSize(QtCore.QSize(24, 24))
        self.mediaShuffleButton_2.setMaximumSize(QtCore.QSize(24, 24))
        self.mediaShuffleButton_2.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/icons/cil-infinity.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mediaShuffleButton_2.setIcon(icon6)
        self.mediaShuffleButton_2.setObjectName("mediaShuffleButton_2")
        self.mediaButtonsHorizontalLayout_2.addWidget(self.mediaShuffleButton_2)
        self.playerLockButton_2 = QtWidgets.QPushButton(self.MediaButtons_2)
        self.playerLockButton_2.setMinimumSize(QtCore.QSize(24, 24))
        self.playerLockButton_2.setMaximumSize(QtCore.QSize(24, 24))
        self.playerLockButton_2.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/icons/cil-notes.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.playerLockButton_2.setIcon(icon7)
        self.playerLockButton_2.setIconSize(QtCore.QSize(20, 20))
        self.playerLockButton_2.setObjectName("playerLockButton_2")
        self.mediaButtonsHorizontalLayout_2.addWidget(self.playerLockButton_2)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.mediaButtonsHorizontalLayout_2.addItem(spacerItem4)
        self.volumeSymbolLabel_2 = QtWidgets.QLabel(self.MediaButtons_2)
        self.volumeSymbolLabel_2.setMinimumSize(QtCore.QSize(16, 16))
        self.volumeSymbolLabel_2.setMaximumSize(QtCore.QSize(16, 16))
        self.volumeSymbolLabel_2.setStyleSheet("QLabel {\n"
"background: transparent;\n"
"color: #FFEEDD;\n"
"font-family: \"Helvetica\", sans-serif;\n"
"}")
        self.volumeSymbolLabel_2.setText("")
        self.volumeSymbolLabel_2.setPixmap(QtGui.QPixmap(":/icons/icons/cil-volume-high.png"))
        self.volumeSymbolLabel_2.setObjectName("volumeSymbolLabel_2")
        self.mediaButtonsHorizontalLayout_2.addWidget(self.volumeSymbolLabel_2)
        self.volumeSlider_2 = QtWidgets.QSlider(self.MediaButtons_2)
        self.volumeSlider_2.setMinimumSize(QtCore.QSize(72, 6))
        self.volumeSlider_2.setStyleSheet("QSlider {\n"
"    background: transparent;\n"
"    height: 5px;\n"
"}\n"
"\n"
"QSlider::groove:horizontal {\n"
"    border: none;\n"
"    height: 5px;\n"
"    background: #33383E; /* Set the same background color as your QProgressBar */\n"
"    border-radius: 2px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"    width: 0px; /* Set the width of the circular handle */\n"
"    background: #4455FF; /* Set the same hover color as your QProgressBar */\n"
"    border-radius: 6px; /* Make it circular by setting half of the width/height */\n"
"}\n"
"\n"
"QSlider::sub-page:horizontal {\n"
"    background: #4B59F1; /* Set the same filled portion color as your QProgressBar */\n"
"    border-radius: 2px;\n"
"}\n"
"")
        self.volumeSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.volumeSlider_2.setObjectName("volumeSlider_2")
        self.mediaButtonsHorizontalLayout_2.addWidget(self.volumeSlider_2)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.mediaButtonsHorizontalLayout_2.addItem(spacerItem5)
        self.appControlButton_2 = QtWidgets.QFrame(self.MediaButtons_2)
        self.appControlButton_2.setStyleSheet("")
        self.appControlButton_2.setObjectName("appControlButton_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.appControlButton_2)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.minimizeButton_2 = QtWidgets.QPushButton(self.appControlButton_2)
        self.minimizeButton_2.setMinimumSize(QtCore.QSize(24, 24))
        self.minimizeButton_2.setMaximumSize(QtCore.QSize(24, 24))
        self.minimizeButton_2.setStyleSheet("QPushButton { \n"
"    background: transparent; border-radius: 0px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:#665622;; \n"
"}\n"
"QPushButton:pressed {\n"
"     background-color: #AAAA00; \n"
"}")
        self.minimizeButton_2.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icons/icons/icon_minimize.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.minimizeButton_2.setIcon(icon8)
        self.minimizeButton_2.setObjectName("minimizeButton_2")
        self.horizontalLayout_4.addWidget(self.minimizeButton_2)
        self.closeButton_2 = QtWidgets.QPushButton(self.appControlButton_2)
        self.closeButton_2.setMinimumSize(QtCore.QSize(24, 24))
        self.closeButton_2.setMaximumSize(QtCore.QSize(24, 24))
        self.closeButton_2.setStyleSheet("QPushButton:hover {\n"
"    background-color:#962128; \n"
"    border-style: none;\n"
"    border-radius: 0px;\n"
"}\n"
"QPushButton:pressed {\n"
"     background-color: #ff0000;\n"
"    border-style: none;\n"
"    border-radius: 0px;\n"
"}")
        self.closeButton_2.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icons/icons/icon_close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.closeButton_2.setIcon(icon9)
        self.closeButton_2.setCheckable(False)
        self.closeButton_2.setObjectName("closeButton_2")
        self.horizontalLayout_4.addWidget(self.closeButton_2)
        self.mediaButtonsHorizontalLayout_2.addWidget(self.appControlButton_2)
        self.mediaButtonsHorizontalLayout_2.setStretch(0, 10)
        self.mediaButtonsHorizontalLayout_2.setStretch(3, 20)
        self.mediaButtonsHorizontalLayout_2.setStretch(4, 100)
        self.mediaButtonsHorizontalLayout_2.setStretch(5, 20)
        self.mediaButtonsHorizontalLayout_2.setStretch(9, 5)
        self.mediaButtonsHorizontalLayout_2.setStretch(13, 10)
        self.mediaButtonsHorizontalLayout_2.setStretch(15, 15)
        self.mediaButtonsHorizontalLayout_2.setStretch(16, 5)
        self.mediaPlayerVerticalLayout_2.addWidget(self.MediaButtons_2)
        self.mediaControlHorizontalLayout_3.addWidget(self.MediaController_2)
        self.mediaControlHorizontalLayout_3.setStretch(0, 3)
        self.verticalLayout.addWidget(self.MediaPlayer)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.playbackTimeLabel_2.setText(_translate("MainWindow", "00:00"))
        self.mediaLenghtLabel_2.setText(_translate("MainWindow", "04:36"))
        self.mediaTitle_2.setText(_translate("MainWindow", "ExampleSong.mp3"))
import res_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
