# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ytdProper.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(706, 514)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("QWidget {\n"
"background-color: #224455;\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setContentsMargins(0, 2, 0, 2)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.VideoPlayer = QtWidgets.QWidget(self.centralwidget)
        self.VideoPlayer.setMinimumSize(QtCore.QSize(480, 270))
        self.VideoPlayer.setStyleSheet("")
        self.VideoPlayer.setObjectName("VideoPlayer")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.VideoPlayer)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.frame = QtWidgets.QFrame(self.VideoPlayer)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(88, 39, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.videoTitleLabel = QtWidgets.QLabel(self.frame)
        self.videoTitleLabel.setMinimumSize(QtCore.QSize(460, 42))
        self.videoTitleLabel.setStyleSheet("QLabel {\n"
"background: transparent;\n"
"color: #FFEEDD;\n"
"font-family: \"Helvetica\", sans-serif;\n"
"font-size: 32px;\n"
"}")
        self.videoTitleLabel.setObjectName("videoTitleLabel")
        self.horizontalLayout_2.addWidget(self.videoTitleLabel)
        spacerItem2 = QtWidgets.QSpacerItem(88, 39, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(1, 5)
        self.horizontalLayout_2.setStretch(2, 1)
        self.verticalLayout.addWidget(self.frame)
        self.verticalLayout_2.addWidget(self.VideoPlayer)
        self.Player = QtWidgets.QFrame(self.centralwidget)
        self.Player.setObjectName("Player")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.Player)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.MediaPlayer = QtWidgets.QFrame(self.Player)
        self.MediaPlayer.setMinimumSize(QtCore.QSize(480, 50))
        self.MediaPlayer.setMaximumSize(QtCore.QSize(16777215, 56))
        self.MediaPlayer.setStyleSheet("")
        self.MediaPlayer.setObjectName("MediaPlayer")
        self.mediaControlHorizontalLayout = QtWidgets.QHBoxLayout(self.MediaPlayer)
        self.mediaControlHorizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.mediaControlHorizontalLayout.setSpacing(0)
        self.mediaControlHorizontalLayout.setObjectName("mediaControlHorizontalLayout")
        self.MediaController = QtWidgets.QFrame(self.MediaPlayer)
        self.MediaController.setMinimumSize(QtCore.QSize(480, 50))
        self.MediaController.setMaximumSize(QtCore.QSize(680, 56))
        self.MediaController.setStyleSheet("QFrame {\n"
"    background-color: #111111;\n"
"    font-family: \"Helvetica\", sans-serif;\n"
"}")
        self.MediaController.setObjectName("MediaController")
        self.mediaPlayerVerticalLayout = QtWidgets.QVBoxLayout(self.MediaController)
        self.mediaPlayerVerticalLayout.setContentsMargins(1, 0, 1, 0)
        self.mediaPlayerVerticalLayout.setSpacing(0)
        self.mediaPlayerVerticalLayout.setObjectName("mediaPlayerVerticalLayout")
        self.MediaProgressBar = QtWidgets.QFrame(self.MediaController)
        self.MediaProgressBar.setStyleSheet("")
        self.MediaProgressBar.setObjectName("MediaProgressBar")
        self.mediaProgressBarHorizontalLayout = QtWidgets.QHBoxLayout(self.MediaProgressBar)
        self.mediaProgressBarHorizontalLayout.setContentsMargins(8, 0, 8, 0)
        self.mediaProgressBarHorizontalLayout.setSpacing(8)
        self.mediaProgressBarHorizontalLayout.setObjectName("mediaProgressBarHorizontalLayout")
        self.playbackTimeLabel = QtWidgets.QLabel(self.MediaProgressBar)
        self.playbackTimeLabel.setMinimumSize(QtCore.QSize(44, 16))
        self.playbackTimeLabel.setMaximumSize(QtCore.QSize(44, 16))
        self.playbackTimeLabel.setStyleSheet("QLabel {\n"
"background: transparent;\n"
"color: #FFEEDD;\n"
"font-family: \"Helvetica\", sans-serif;\n"
"}")
        self.playbackTimeLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.playbackTimeLabel.setObjectName("playbackTimeLabel")
        self.mediaProgressBarHorizontalLayout.addWidget(self.playbackTimeLabel)
        self.playbackProgress = QtWidgets.QSlider(self.MediaProgressBar)
        self.playbackProgress.setMinimumSize(QtCore.QSize(360, 8))
        self.playbackProgress.setMaximumSize(QtCore.QSize(16777215, 8))
        self.playbackProgress.setStyleSheet("QSlider {\n"
"    background: transparent;\n"
"    height: 6px;\n"
"}\n"
"\n"
"QSlider::groove:horizontal {\n"
"    border: none;\n"
"    height: 6px;\n"
"    background: #33383E;\n"
"    border-radius: 3px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"    width: 6px;\n"
"    background: #22272d;\n"
"    border-radius: 3px;\n"
"}\n"
"\n"
"QSlider::sub-page:horizontal {\n"
"    background: #F1594B;\n"
"    margin-left: 2px;\n"
"    width: 6px;\n"
"    border-radius: 3px;\n"
"}\n"
"")
        self.playbackProgress.setMaximum(499)
        self.playbackProgress.setOrientation(QtCore.Qt.Horizontal)
        self.playbackProgress.setObjectName("playbackProgress")
        self.mediaProgressBarHorizontalLayout.addWidget(self.playbackProgress)
        self.mediaLenghtLabel = QtWidgets.QLabel(self.MediaProgressBar)
        self.mediaLenghtLabel.setMinimumSize(QtCore.QSize(44, 16))
        self.mediaLenghtLabel.setMaximumSize(QtCore.QSize(44, 16))
        self.mediaLenghtLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.mediaLenghtLabel.setStyleSheet("QLabel {\n"
"background: transparent;\n"
"color: #FFEEDD;\n"
"font-family: \"Helvetica\", sans-serif;\n"
"}")
        self.mediaLenghtLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.mediaLenghtLabel.setObjectName("mediaLenghtLabel")
        self.mediaProgressBarHorizontalLayout.addWidget(self.mediaLenghtLabel)
        self.mediaPlayerVerticalLayout.addWidget(self.MediaProgressBar)
        self.MediaButtons = QtWidgets.QFrame(self.MediaController)
        self.MediaButtons.setStyleSheet("QFrame {\n"
"    background-color: #0F111A; \n"
"}\n"
"\n"
"QPushButton { \n"
"    background: transparent; border: none;  border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color:#33383E; \n"
"    border-style: solid; \n"
"    border-radius: 2px; \n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"     background-color: #4455FF; \n"
"    border-style: solid; \n"
"    border-radius: 2px; \n"
"}")
        self.MediaButtons.setObjectName("MediaButtons")
        self.mediaButtonsHorizontalLayout = QtWidgets.QHBoxLayout(self.MediaButtons)
        self.mediaButtonsHorizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.mediaButtonsHorizontalLayout.setSpacing(2)
        self.mediaButtonsHorizontalLayout.setObjectName("mediaButtonsHorizontalLayout")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.mediaButtonsHorizontalLayout.addItem(spacerItem4)
        self.fileOpenerButton = QtWidgets.QPushButton(self.MediaButtons)
        self.fileOpenerButton.setMinimumSize(QtCore.QSize(24, 24))
        self.fileOpenerButton.setMaximumSize(QtCore.QSize(24, 24))
        self.fileOpenerButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/cil-folder-open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.fileOpenerButton.setIcon(icon)
        self.fileOpenerButton.setObjectName("fileOpenerButton")
        self.mediaButtonsHorizontalLayout.addWidget(self.fileOpenerButton)
        self.playerLockButton = QtWidgets.QPushButton(self.MediaButtons)
        self.playerLockButton.setMinimumSize(QtCore.QSize(24, 24))
        self.playerLockButton.setMaximumSize(QtCore.QSize(24, 24))
        self.playerLockButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/cil-lock-locked.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.playerLockButton.setIcon(icon1)
        self.playerLockButton.setObjectName("playerLockButton")
        self.mediaButtonsHorizontalLayout.addWidget(self.playerLockButton)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.mediaButtonsHorizontalLayout.addItem(spacerItem5)
        self.mediaTitle = QtWidgets.QLabel(self.MediaButtons)
        self.mediaTitle.setMinimumSize(QtCore.QSize(60, 0))
        self.mediaTitle.setStyleSheet("QLabel {\n"
"background: transparent;\n"
"color: #FFEEDD;\n"
"font-family: \"Helvetica\", sans-serif;\n"
"}")
        self.mediaTitle.setObjectName("mediaTitle")
        self.mediaButtonsHorizontalLayout.addWidget(self.mediaTitle)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.mediaButtonsHorizontalLayout.addItem(spacerItem6)
        self.mediaPreviousButton = QtWidgets.QPushButton(self.MediaButtons)
        self.mediaPreviousButton.setMinimumSize(QtCore.QSize(24, 24))
        self.mediaPreviousButton.setMaximumSize(QtCore.QSize(24, 24))
        self.mediaPreviousButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/cil-media-step-backward.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mediaPreviousButton.setIcon(icon2)
        self.mediaPreviousButton.setIconSize(QtCore.QSize(20, 20))
        self.mediaPreviousButton.setObjectName("mediaPreviousButton")
        self.mediaButtonsHorizontalLayout.addWidget(self.mediaPreviousButton)
        self.mediaPlayPauseButton = QtWidgets.QPushButton(self.MediaButtons)
        self.mediaPlayPauseButton.setMinimumSize(QtCore.QSize(24, 24))
        self.mediaPlayPauseButton.setMaximumSize(QtCore.QSize(24, 24))
        self.mediaPlayPauseButton.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons/cil-media-play.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mediaPlayPauseButton.setIcon(icon3)
        self.mediaPlayPauseButton.setIconSize(QtCore.QSize(20, 20))
        self.mediaPlayPauseButton.setObjectName("mediaPlayPauseButton")
        self.mediaButtonsHorizontalLayout.addWidget(self.mediaPlayPauseButton)
        self.mediaNextButton = QtWidgets.QPushButton(self.MediaButtons)
        self.mediaNextButton.setMinimumSize(QtCore.QSize(24, 24))
        self.mediaNextButton.setMaximumSize(QtCore.QSize(24, 24))
        self.mediaNextButton.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/icons/cil-media-step-forward.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mediaNextButton.setIcon(icon4)
        self.mediaNextButton.setIconSize(QtCore.QSize(20, 20))
        self.mediaNextButton.setObjectName("mediaNextButton")
        self.mediaButtonsHorizontalLayout.addWidget(self.mediaNextButton)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.mediaButtonsHorizontalLayout.addItem(spacerItem7)
        self.mediaRepeatButton = QtWidgets.QPushButton(self.MediaButtons)
        self.mediaRepeatButton.setMinimumSize(QtCore.QSize(24, 24))
        self.mediaRepeatButton.setMaximumSize(QtCore.QSize(24, 24))
        self.mediaRepeatButton.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/icons/cil-loop.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mediaRepeatButton.setIcon(icon5)
        self.mediaRepeatButton.setIconSize(QtCore.QSize(20, 20))
        self.mediaRepeatButton.setObjectName("mediaRepeatButton")
        self.mediaButtonsHorizontalLayout.addWidget(self.mediaRepeatButton)
        self.mediaShuffleButton = QtWidgets.QPushButton(self.MediaButtons)
        self.mediaShuffleButton.setMinimumSize(QtCore.QSize(24, 24))
        self.mediaShuffleButton.setMaximumSize(QtCore.QSize(24, 24))
        self.mediaShuffleButton.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/icons/cil-infinity.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mediaShuffleButton.setIcon(icon6)
        self.mediaShuffleButton.setObjectName("mediaShuffleButton")
        self.mediaButtonsHorizontalLayout.addWidget(self.mediaShuffleButton)
        self.mediaAudioTrack = QtWidgets.QPushButton(self.MediaButtons)
        self.mediaAudioTrack.setMinimumSize(QtCore.QSize(24, 24))
        self.mediaAudioTrack.setMaximumSize(QtCore.QSize(24, 24))
        self.mediaAudioTrack.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/icons/cil-notes.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mediaAudioTrack.setIcon(icon7)
        self.mediaAudioTrack.setIconSize(QtCore.QSize(20, 20))
        self.mediaAudioTrack.setObjectName("mediaAudioTrack")
        self.mediaButtonsHorizontalLayout.addWidget(self.mediaAudioTrack)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.mediaButtonsHorizontalLayout.addItem(spacerItem8)
        self.mediaMuteButton = QtWidgets.QPushButton(self.MediaButtons)
        self.mediaMuteButton.setMinimumSize(QtCore.QSize(16, 16))
        self.mediaMuteButton.setMaximumSize(QtCore.QSize(16, 16))
        self.mediaMuteButton.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icons/icons/cil-volume-high.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mediaMuteButton.setIcon(icon8)
        self.mediaMuteButton.setObjectName("mediaMuteButton")
        self.mediaButtonsHorizontalLayout.addWidget(self.mediaMuteButton)
        self.volumeSlider = QtWidgets.QSlider(self.MediaButtons)
        self.volumeSlider.setMinimumSize(QtCore.QSize(72, 6))
        self.volumeSlider.setStyleSheet("QSlider {\n"
"    background: transparent;\n"
"    height: 5px;\n"
"}\n"
"\n"
"QSlider::groove:horizontal {\n"
"    border: none;\n"
"    height: 5px;\n"
"    background: #33383E;\n"
"    border-radius: 2px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"    width: 5px;\n"
"    background: #22272d;\n"
"    border-radius: 2px;\n"
"}\n"
"\n"
"QSlider::sub-page:horizontal {\n"
"    background: #4b59f1;\n"
"    margin-left: 2px;\n"
"    width: 5px;\n"
"    border-radius: 2px;\n"
"}\n"
"\n"
"")
        self.volumeSlider.setOrientation(QtCore.Qt.Horizontal)
        self.volumeSlider.setObjectName("volumeSlider")
        self.mediaButtonsHorizontalLayout.addWidget(self.volumeSlider)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.mediaButtonsHorizontalLayout.addItem(spacerItem9)
        self.appControlButton = QtWidgets.QFrame(self.MediaButtons)
        self.appControlButton.setStyleSheet("")
        self.appControlButton.setObjectName("appControlButton")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.appControlButton)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.minimizeButton = QtWidgets.QPushButton(self.appControlButton)
        self.minimizeButton.setMinimumSize(QtCore.QSize(24, 24))
        self.minimizeButton.setMaximumSize(QtCore.QSize(24, 24))
        self.minimizeButton.setStyleSheet("QPushButton { \n"
"    background: transparent; border-radius: 0px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:#665622;; \n"
"}\n"
"QPushButton:pressed {\n"
"     background-color: #AAAA00; \n"
"}")
        self.minimizeButton.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icons/icons/icon_minimize.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.minimizeButton.setIcon(icon9)
        self.minimizeButton.setObjectName("minimizeButton")
        self.horizontalLayout_3.addWidget(self.minimizeButton)
        self.closeButton = QtWidgets.QPushButton(self.appControlButton)
        self.closeButton.setMinimumSize(QtCore.QSize(24, 24))
        self.closeButton.setMaximumSize(QtCore.QSize(24, 24))
        self.closeButton.setStyleSheet("QPushButton:hover {\n"
"    background-color:#962128; \n"
"    border-style: none;\n"
"    border-radius: 0px;\n"
"}\n"
"QPushButton:pressed {\n"
"     background-color: #ff0000;\n"
"    border-style: none;\n"
"    border-radius: 0px;\n"
"}")
        self.closeButton.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/icons/icons/icon_close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.closeButton.setIcon(icon10)
        self.closeButton.setCheckable(False)
        self.closeButton.setObjectName("closeButton")
        self.horizontalLayout_3.addWidget(self.closeButton)
        self.mediaButtonsHorizontalLayout.addWidget(self.appControlButton)
        self.mediaButtonsHorizontalLayout.setStretch(0, 10)
        self.mediaButtonsHorizontalLayout.setStretch(3, 20)
        self.mediaButtonsHorizontalLayout.setStretch(4, 100)
        self.mediaButtonsHorizontalLayout.setStretch(5, 20)
        self.mediaButtonsHorizontalLayout.setStretch(9, 5)
        self.mediaButtonsHorizontalLayout.setStretch(13, 10)
        self.mediaButtonsHorizontalLayout.setStretch(15, 15)
        self.mediaButtonsHorizontalLayout.setStretch(16, 5)
        self.mediaPlayerVerticalLayout.addWidget(self.MediaButtons)
        self.mediaControlHorizontalLayout.addWidget(self.MediaController)
        self.mediaControlHorizontalLayout.setStretch(0, 3)
        self.horizontalLayout.addWidget(self.MediaPlayer)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem10)
        self.verticalLayout_2.addWidget(self.Player)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.videoTitleLabel.setText(_translate("MainWindow", "Example Video Title"))
        self.playbackTimeLabel.setText(_translate("MainWindow", "00:20:43"))
        self.mediaLenghtLabel.setText(_translate("MainWindow", "02:10:09"))
        self.mediaTitle.setText(_translate("MainWindow", "ExampleSong.mp3"))
import res_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
